### PR TITLE
Setting for additional arguments, and a popup for user input support.

### PR DESCRIPTION
**Pull request by pzahra**
Compile the ant input handler with the batch file, and place it in the `ant\lib` folder. You can now use the new Additional Arguments setting to tell ant how to use the `<input>` task.

### CODE REVIEW

**Comment by SlavaRa** [comment]
thank, but I have to check how it works

**Comment by pzahra** [comment]
Here's what I used for testing:

```
	<target name="InputTest" description="Test the Input tag">
		<input message="press return key" />
		<input message="give me a word" addproperty="word" />
		<input message="select one" addproperty="final" validargs="item a,item b,item c,item d,${word}" />
		<echo message="${final}" />
	</target>
```

The input window could be made bigger and centred, but I'm not a java guy and had to make that by hand. It does the job though. The first popup still has a textbox because it has no way of knowing it won't be assigned to anything, and the third uses a dropdown for all valid inputs.

**Comment by pzahra** [comment]
The only change to the plugin itself is the `Additional Arguments` setting which places the raw string directly before `-buildfile`. With this you can add whatever you want to the ant command; the input popup, being the most requested, can be achieved by adding the new java classes to the scope of `ant\lib` and the `-inputhandler` argument, but of course anyone can point to their own without any trouble.

**Comment by SlavaRa** [comment]
Now i will merge this PR. But i think that all this can be done from C#

**Pull request merged**
